### PR TITLE
Implement line labels tool. 

### PR DESCRIPTION
**Pull request by ibusko**
This PR implements basically the same functionality we have in specviz v.0.5.0 for the display of line labels. Two features are still missing, although they aren't blockers:
- The "Read", "Write", and "Export" buttons for handling files with line lists created from the plotted labels, are still missing.
- The Line Labels button icon needs to be more informative. For now, I'm using a `folder-2.svg` icon.

The `.ui` files that I had created for the line list tool window and its dialog box, somehow disappeared and I have to re-create them from scratch. This will be the subject of another PR.

After this work is completed, there will be likely some code refactoring and cleanup. That's not a blocker for a release though.

### CODE REVIEW

**Comment by javerbukh** [comment]
@ibusko I'm currently testing this, here are some observations:
1. I select a line, dialog box pops up, "0 lines included in range". Is there a line type/minimum wave/maximum wave combo I could use to change this?
2. If I press OK with `0 lines included in range` still there, I go back to initial state of the Line Labels Tool. Is this the expected functionality?
3. If I press the `Draw` button, the tool crashes with the traceback
```Traceback (most recent call last):
  File "/Users/javerbukh/Documents/specviz/specviz/widgets/linelists_window.py", line 290, in <lambda>
    caller=self.plot_window))
  File "/Users/javerbukh/Documents/specviz/specviz/widgets/line_labels_plotter.py", line 114, in plot_linelists
    merged_linelist = LineList.merge(linelists_with_selections, units)
  File "/Users/javerbukh/Documents/specviz/specviz/core/linelist.py", line 291, in merge
    merged_table = vstack(tables)
  File "/Users/javerbukh/miniconda3/envs/specviz_dev_env/lib/python3.6/site-packages/astropy/table/operations.py", line 276, in vstack
    tables = _get_list_of_tables(tables)  # validates input
  File "/Users/javerbukh/miniconda3/envs/specviz_dev_env/lib/python3.6/site-packages/astropy/table/operations.py", line 49, in _get_list_of_tables
    raise TypeError('`tables` arg must be a Table or sequence of Tables or Rows')
TypeError: `tables` arg must be a Table or sequence of Tables or Rows
Abort trap: 6```

**Comment by ibusko** [comment]
If 0 lines are included in range, you can type in wavelength values that force the tool to get lines from the table. That's table-dependent, of course. You can see the range spanned by each line list in the drop down menu itself. 

As for the crash, that's ideed a bug. I'll fix it and commit to the PR.

**Comment by javerbukh** [comment]
Looks great! Nice job!

**Comment by nmearl** [comment]
Line lists should really be implemented as plugin, and not built into the core. I've opened #487 to make sure we re-address this in the future.

**Comment by ibusko** [comment]
@nmearl indeed, this implementation is just a quick-and-dirty port of the existing code in v.0.5 so that we can have the functionality in place for this release. I intend to adress the refactoring as the next step in development.

**Pull request merged**
