### PR TITLE
Minor tweaks; move Glue plugin interface into SpecViz package

### PR DESCRIPTION
**Pull request by nmearl**
Provides minor changes to user experience. Brings the interface layer between specviz that operates when specviz is opened in Glue into this repository.

### CODE REVIEW

**Comment by astrofrog** [comment]
@nmearl - just to check, do you want to then later remove the separate plugin, and have the main version be here?

**Comment by nmearl** [comment]
@astrofrog I'm not sure I follow? The plugin facilitates communication between glue and specviz when specviz is opened within Glue.

**Comment by astrofrog** [comment]
@nmearl - sorry, I should have been clearer - at the moment, are you still considering https://github.com/glue-viz/glue-specviz to be the authoritative version of what you are adding here in ``external``? Or do you want to consider the version in this PR and repo to be the main one, and get rid of https://github.com/glue-viz/glue-specviz?

**Comment by nmearl** [comment]
@astrofrog Ah, I see what you mean. I'm hoping to make this one the main one, and remove the one at https://github.com/glue-viz/glue-specviz. Seems like we can have glue integration for free if just include it with specviz from the get-go.

**Pull request merged**
