### PR TITLE
Implements #291 - Incorporate line lists

### PR DESCRIPTION
**Pull request by ibusko**

### CODE REVIEW

**Comment by kassin** [comment]
@ibusko Looks great!  Would you possibly be able to walk @nmearl, Tony Marston, and me through these changes?  Afterwards, I'd like to start users on testing the line lists.

**Comment by ibusko** [comment]
Sure!

**Comment by ibusko** [comment]
I believe the line labels functionality is at a point were it can be made available to interested users/testers. It contains at this point, in a way or another, all requirements that were laid down in our past meetings and are listed in the specviz/data/linelists/DEV_NOTES.txt document.

**Comment by nmearl** [comment]
Once the conflict is fixed, we can merge this.

**Pull request merged**
