### PR TITLE
Fix bug in load file dialog

### PR DESCRIPTION
**Pull request by drdavella**
This was a regression introduced by #616. This PR fixes the bug and adds a test to try to prevent it from cropping up again. However, this is a pretty tight corner between our application logic and Qt-specific components, so it's rather difficult to test properly.

### CODE REVIEW

**Comment by nmearl** [comment]
I'm actually thinking that hitting these issues where the solution is "make a clear delineation between ui-logic and testable, core functionality" might be a good thing overall, if a bit tedious and frustrating to have to solve. This looks good!

**Comment by drdavella** [comment]
@nmearl cool, there will be some more refactoring to that effect (out of necessity) in a forthcoming PR.

The problem is that the boundary will still be very difficult to test, but at some point we're just hitting on the limitations of the tools that we have.

**Comment by drdavella** [comment]
Going ahead and merging this so the bug fix is available.

**Comment by drdavella** [comment]
@kassin this should fix the issue on `master` that you reported.

**Pull request merged**
