### PR TITLE
Require pycodestyle to pass and fix errors

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes https://github.com/spacetelescope/specviz/issues/545

### CODE REVIEW

**Comment by astrofrog** [comment]
The pycodestyle job on Travis is passing, so this is good to go once approved

**Comment by nmearl** [comment]
Could you rebase with #614 to remove the python 3.5 dependency (and failing associated tests)?

**Comment by astrofrog** [comment]
@nmearl - done!

**Comment by nmearl** [comment]
Ah, sorry @astrofrog. One more rebase? 😅

**Comment by astrofrog** [comment]
Rebased again to resolve conflicts

**Pull request merged**
