### PR TITLE
Thicker plot lines and thicker slider line

### PR DESCRIPTION
**Pull request by brechmos-stsci**
There were several requests to make the plot lines thicker as they are hard to see in the cubeviz window. I think it might make sense here if you are good with it. I also made the green line, that represents the spatial slice location, thicker as it was hard to see.

### CODE REVIEW

**Comment by nmearl** [comment]
Plot lines can already be made thicker using plot settings in SpecViz.

**Comment by brechmos-stsci** [comment]
Oh... didn't see that, can you post an example?  I don't see it. Is it in `SpecVizViewer`?

**Comment by nmearl** [comment]
screen shot 2018-03-16 at 3 04 50 pm

**Comment by brechmos-stsci** [comment]
Oh, yeah, knew that was there. I am looking for a programmatic one so the default (in cubeviz) is a thicker line.

**Comment by nmearl** [comment]
You should not be doing that here, then, since this would affect specviz as a whole. While it's fine to change the wavelength slider width in the code, to change the default plotted line width, you should add it into the style parameters on line 240 (and pull the latest specviz):

```python
dispatch.on_add_to_window.emit(data=spec_data,
                               style={'color': layer.style.rgba[:3],
                                      'line_width': 3})
```

**Comment by brechmos-stsci** [comment]
Ok, so I changed it so that it is only the slider line being thicker.  I'll look at changing the other ones via cubeviz.

**Pull request merged**
